#
# This file contains expected test output data generated by PBBT.
#
---
suite: rex.ctl
tests:
- sh: ln -s ../test/rex-helper ./sandbox/rex
  stdout: ''
- sh: pip install -q -e ./demo/rex.ctl_demo
  stdout: ''
- suite: rex-serve
  tests:
  - suite: task-description
    tests:
    - sh: ./sandbox/rex help serve
      stdout: |+
        SERVE - starts HTTP server
        Usage: rex serve [<project>]

        The serve task starts an HTTP server to serve a Rex application.

        This task takes one argument: the name of the primary Rex package.
        Alternatively, the package could be specified using project
        setting.

        Use option --require or setting requirements to specify
        additional packages to include with the application.

        Use option --set or setting settings to specify configuration
        parameters of the application.

        Use options --host and --port or settings http-host and
        http-port to specify the address and the port number for the
        HTTP server.  If neither are set, the server is started on
        127.0.0.1:8080.

        By default, the server dumps HTTP logs in Apache Common Log Format
        to stdout.  Use option --quiet to suppress this output.
        Unhandled application exceptions are dumped to stderr.

        Toggle debug setting to run the application in debug mode and
        report unhandled exceptions to the client.

        Options:
          --require=PACKAGE        : include an additional package
          --set=PARAM=VALUE        : set a configuration parameter
          -h/--host=HOSTNAME       : host name for the HTTP server
          -p/--port=PORT           : port number for the HTTP server
          -q/--quiet               : suppress HTTP logs

    - sh: ./sandbox/rex help http-host
      stdout: |+
        HTTP-HOST - HTTP server address
        Usage: rex --http-host=VALUE
               http-host: VALUE (rex.yaml)
               REX_HTTP_HOST=VALUE (environment)

        This parameter specifies the default address for the HTTP server.

    - sh: ./sandbox/rex help http-port
      stdout: |+
        HTTP-PORT - HTTP server port
        Usage: rex --http-port=VALUE
               http-port: VALUE (rex.yaml)
               REX_HTTP_PORT=VALUE (environment)

        This parameter specifies the default port number for the HTTP
        server.

  - suite: run-with-no-project
    tests:
    - sh: ./sandbox/rex --daemon serve
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 404 Not Found
        Date: Thu, 13 Jun 2013 21:18:48 GMT
        Content-Length: 41
        Content-Type: text/plain
        Server: WSGIServer/0.1 Python/2.7.4

        Application does not provide web access.
    - sh: ./sandbox/rex --kill serve
      stdout: |+
        Serving on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:05:08] "GET / HTTP/1.1" 404 41

  - suite: run-with-a-project
    tests:
    - sh: ./sandbox/rex --daemon serve rex.ctl_demo
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:01 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --kill serve rex.ctl_demo
      stdout: |+
        Serving rex.ctl_demo on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:05:16] "GET / HTTP/1.1" 200 55

  - suite: specify-the-project-using-project
    tests:
    - sh: ./sandbox/rex --daemon --project=rex.ctl_demo serve
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:03 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --kill --project=rex.ctl_demo serve
      stdout: |+
        Serving rex.ctl_demo on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:05:23] "GET / HTTP/1.1" 200 55

  - suite: server-address-with-http-host-and-http-port
    tests:
    - sh: ./sandbox/rex --daemon --http-host=localhost --http-port=8088 serve rex.ctl_demo
      stdout: ''
    - sh: ./sandbox/rex --get http://localhost:8088/
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:05 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --kill --http-host=localhost --http-port=8088 serve rex.ctl_demo
      stdout: |+
        Serving rex.ctl_demo on localhost:8088
        localhost - - [13/Jun/2013 16:05:27] "GET / HTTP/1.1" 200 55

  - suite: server-address-with-host-and-port
    tests:
    - sh: ./sandbox/rex --daemon --http-host=localhost --http-port=8088 serve rex.ctl_demo
        -h 127.0.0.1 -p 8080
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:06 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --kill --http-host=localhost --http-port=8088 serve rex.ctl_demo
        -h 127.0.0.1 -p 8080
      stdout: |+
        Serving rex.ctl_demo on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:05:38] "GET / HTTP/1.1" 200 55

  - suite: invalid-http-host-and-http-port
    tests:
    - sh: ./sandbox/rex serve
      stdout: |+
        FATAL ERROR: invalid value for setting --http-host: expected a host name or an IP address

    - sh: ./sandbox/rex serve
      stdout: |
        Serving on 256.56.6.0:8080
        [Errno -2] Name or service not known
    - sh: ./sandbox/rex serve
      stdout: |+
        FATAL ERROR: invalid value for setting --http-port: expected a port number

    - sh: ./sandbox/rex serve
      stdout: |+
        FATAL ERROR: invalid value for setting --http-port: invalid literal for int() with base 10: 'localhost'

    - sh: ./sandbox/rex serve
      stdout: |+
        FATAL ERROR: invalid value for setting --http-port: expected a port number

    - sh: ./sandbox/rex serve
      stdout: |
        Serving on 127.0.0.1:80
        [Errno 13] Permission denied
  - suite: http-auth
    tests:
    - sh: ./sandbox/rex --daemon serve rex.ctl_demo
      stdout: ''
    - sh: ./sandbox/rex --get http://Aladdin@localhost:8080/
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:09 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --get http://Aladdin:open%20sesame@localhost:8080/
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:11 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --kill serve rex.ctl_demo
      stdout: |+
        Serving rex.ctl_demo on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:06:09] "GET / HTTP/1.1" 200 55
        localhost - Aladdin [13/Jun/2013 16:06:11] "GET / HTTP/1.1" 200 55

  - suite: unhandled-exceptions
    tests:
    - sh: ./sandbox/rex --daemon serve rex.ctl_demo
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:13 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --get /error
      stdout: |
        HTTP/1.0 500 Internal Server Error
        Date: Thu, 13 Jun 2013 21:19:14 GMT
        Content-Length: 59
        Content-Type: text/plain
        Server: WSGIServer/0.1 Python/2.7.4

        A server error occurred.  Please contact the administrator.
    - sh: ./sandbox/rex --kill serve rex.ctl_demo
      stdout: |+
        Serving rex.ctl_demo on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:07:21] "GET / HTTP/1.1" 200 55
        ----------------------------------------------------------------------
        [2013-06-13 16:07:21.367336] GET http://127.0.0.1:8080/error HTTP/1.1
        Traceback (most recent call last):
          File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
            self.result = application(self.environ, self.start_response)
          File "/home/xi/xitology/prometheus/rex/rex.core-opensource/src/rex/core/application.py", line 84, in __call__
            output = wsgi(environ, start_response)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 328, in __call__
            resp = self.handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 110, in __call__
            resp = self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 140, in __call__
            return self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 174, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 253, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 271, in __call__
            return handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/command.py", line 69, in __call__
            return self.render(req, **arguments)
          File "/home/xi/xitology/prometheus/rex/rex.ctl-opensource/demo/rex.ctl_demo/src/rex/ctl_demo.py", line 23, in render
            raise RuntimeError("some unexpected problem occurred")
        RuntimeError: some unexpected problem occurred
        localhost - - [13/Jun/2013 16:07:21] "GET /error HTTP/1.1" 500 59

  - suite: unhandled-exceptions-with-debug
    tests:
    - sh: ./sandbox/rex --daemon --debug serve rex.ctl_demo
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:15 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --get /error
      stdout: |
        HTTP/1.0 500 Internal Server Error
        Date: Thu, 13 Jun 2013 21:19:16 GMT
        Content-Type: text/plain
        Server: WSGIServer/0.1 Python/2.7.4

        A server error occurred.  Please contact the administrator.

        [2013-06-13 16:19:16.250977] GET http://127.0.0.1:8080/error HTTP/1.1
        Traceback (most recent call last):
          File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
            self.result = application(self.environ, self.start_response)
          File "/home/xi/xitology/prometheus/rex/rex.core-opensource/src/rex/core/application.py", line 84, in __call__
            output = wsgi(environ, start_response)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 328, in __call__
            resp = self.handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 110, in __call__
            resp = self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 140, in __call__
            return self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 174, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 253, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 271, in __call__
            return handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/command.py", line 69, in __call__
            return self.render(req, **arguments)
          File "/home/xi/xitology/prometheus/rex/rex.ctl-opensource/demo/rex.ctl_demo/src/rex/ctl_demo.py", line 23, in render
            raise RuntimeError("some unexpected problem occurred")
        RuntimeError: some unexpected problem occurred
    - sh: ./sandbox/rex --kill --debug serve rex.ctl_demo
      stdout: |
        # loading extensions from serve = rex.ctl.serve
        # loading extensions from common = rex.ctl.common
        Serving rex.ctl_demo on 127.0.0.1:8080
        localhost - - [13/Jun/2013 16:07:36] "GET / HTTP/1.1" 200 55
        ----------------------------------------------------------------------
        [2013-06-13 16:07:38.101790] GET http://127.0.0.1:8080/error HTTP/1.1
        Traceback (most recent call last):
          File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
            self.result = application(self.environ, self.start_response)
          File "/home/xi/xitology/prometheus/rex/rex.core-opensource/src/rex/core/application.py", line 84, in __call__
            output = wsgi(environ, start_response)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 328, in __call__
            resp = self.handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 110, in __call__
            resp = self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 140, in __call__
            return self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 174, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 253, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 271, in __call__
            return handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/command.py", line 69, in __call__
            return self.render(req, **arguments)
          File "/home/xi/xitology/prometheus/rex/rex.ctl-opensource/demo/rex.ctl_demo/src/rex/ctl_demo.py", line 23, in render
            raise RuntimeError("some unexpected problem occurred")
        RuntimeError: some unexpected problem occurred
        localhost - - [13/Jun/2013 16:07:38] "GET /error HTTP/1.1" 500 1620
  - suite: the-quiet-option
    tests:
    - sh: ./sandbox/rex --daemon serve rex.ctl_demo --quiet
      stdout: ''
    - sh: ./sandbox/rex --get /
      stdout: |
        HTTP/1.0 200 OK
        Date: Thu, 13 Jun 2013 21:19:19 GMT
        Content-Length: 55
        Content-Type: text/html; charset=UTF-8
        Server: WSGIServer/0.1 Python/2.7.4

        <!DOCTYPE html>
        <title>Welcome to REX.CTL_DEMO!</title>
    - sh: ./sandbox/rex --get /error
      stdout: |
        HTTP/1.0 500 Internal Server Error
        Date: Thu, 13 Jun 2013 21:19:20 GMT
        Content-Length: 59
        Content-Type: text/plain
        Server: WSGIServer/0.1 Python/2.7.4

        A server error occurred.  Please contact the administrator.
    - sh: ./sandbox/rex --kill serve rex.ctl_demo --quiet
      stdout: |+
        ----------------------------------------------------------------------
        [2013-06-13 16:07:55.114582] GET http://127.0.0.1:8080/error HTTP/1.1
        Traceback (most recent call last):
          File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
            self.result = application(self.environ, self.start_response)
          File "/home/xi/xitology/prometheus/rex/rex.core-opensource/src/rex/core/application.py", line 84, in __call__
            output = wsgi(environ, start_response)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 328, in __call__
            resp = self.handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 110, in __call__
            resp = self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 140, in __call__
            return self.trunk(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 174, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 253, in __call__
            return self.fallback(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/route.py", line 271, in __call__
            return handler(req)
          File "/home/xi/xitology/prometheus/rex/rex.web-opensource/src/rex/web/command.py", line 69, in __call__
            return self.render(req, **arguments)
          File "/home/xi/xitology/prometheus/rex/rex.ctl-opensource/demo/rex.ctl_demo/src/rex/ctl_demo.py", line 23, in render
            raise RuntimeError("some unexpected problem occurred")
        RuntimeError: some unexpected problem occurred

- sh: pip uninstall -q -y rex.ctl_demo
  stdout: ''
- py: load-accumulated-coverage-data
  stdout: ''
